# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CriaAPP
                                 A QGIS plugin
 Este plugin cria APP
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-06-26
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Thalita Mascarenhas
        email                : thalitamascarenhas@ufpr.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import *

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .CriaAPP_dialog import CriaAPPDialog
import os.path
import processing
import sys, os
from osgeo import ogr


class CriaAPP:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'CriaAPP_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&CriaAPP')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CriaAPP', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/CriaAPP/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'CriaAPP'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&CriaAPP'),
                action)
            self.iface.removeToolBarIcon(action)
    
    def carregaVetorN(self):
        self.dlg.comboBox.clear()
        lista_layers = [layer for layer in QgsProject.instance().mapLayers().values()]
        lista_layers_vetor = []
        for layer in lista_layers:
            if layer.type() == QgsMapLayer.VectorLayer:
                lista_layers_vetor.append(layer.name())
        self.dlg.comboBox.addItems(lista_layers_vetor)
    
    def carregaVetorH(self):
        self.dlg.comboBox_2.clear()
        lista_layers2 = [layer for layer in QgsProject.instance().mapLayers().values()]
        lista_layers_vetor2 = []
        for layer in lista_layers2:
            if layer.type() == QgsMapLayer.VectorLayer:
                lista_layers_vetor2.append(layer.name())
        self.dlg.comboBox_2.addItems(lista_layers_vetor2)

    def carregaVetorP(self):
        self.dlg.comboBox_3.clear()
        lista_layers3 = [layer for layer in QgsProject.instance().mapLayers().values()]
        lista_layers_vetor3 = []
        for layer in lista_layers3:
            if layer.type() == QgsMapLayer.VectorLayer:
                lista_layers_vetor3.append(layer.name())
        self.dlg.comboBox_3.addItems(lista_layers_vetor3)
    
    def VetorN_Entrada(self):
        layer1 = None
        nomecamada = self.dlg.comboBox.currentText()
        for lyr in QgsProject.instance().mapLayers().values():
            if lyr.name() == nomecamada:
                layer1 = lyr
                break
        return layer1
    
    def VetorH_Entrada(self):
        layer2 = None
        nomecamada = self.dlg.comboBox_2.currentText()
        for lyr in QgsProject.instance().mapLayers().values():
            if lyr.name() == nomecamada:
                layer2 = lyr
                break
        return layer2
    
    def VetorP_Entrada(self):
        layer3 = None
        nomecamada = self.dlg.comboBox_3.currentText()
        for lyr in QgsProject.instance().mapLayers().values():
            if lyr.name() == nomecamada:
                layer3 = lyr
                break
        return layer3
    
    
    def variaveis(self):
        self.camadaN = self.VetorN_Entrada()
        self.camadaH = self.VetorH_Entrada()
        self.camadaP = self.VetorP_Entrada()
        self.largura = self.dlg.spinBox.value()

    


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = CriaAPPDialog()

        # show the dialog
        self.dlg.show()

        self.carregaVetorN()
        self.carregaVetorH()
        self.carregaVetorP()
        
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            self.variaveis()
            

            processing.runAndLoadResults("model:APP", {'area':self.camadaP,
                                                       'hidrografia':self.camadaH,
                                                       'margem':self.largura,
                                                       'nascente':self.camadaN,
                                                       'native:clip_1:APP':'TEMPORARY_OUTPUT'})
            

            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
